;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	c-electric-star
	end-of-buffer
	ido-find-file
	ido-switch-buffer
	isearch-repeat-forward
	kill-region
	mark-whole-buffer
	mouse-set-region
	ns-copy-including-secondary
	smex
	yas-expand
	))
